spring:
  application:
    name: hello
  cloud:
    kubernetes:
      config:
        name: helloapp-configmap
        namespace: default
        sources:
          - name: helloapp-configmap
      reload:
        enabled: true
        mode: event
        monitoring-config-maps: true


logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG

server:
  port: 8080
  servlet:
    context-path: /